import { Champion, Classes, Names, Origins } from "../interfaces";

export const SET6: Champion[] = [
  {
    name: Names.Caitlyn,
    set: 6,
    class1: Classes.Sniper,
    origin1: Origins.Enforcer,
    cost: 1,
    range: 4,
  },
  {
    name: Names.Camille,
    set: 6,
    class1: Classes.Challenger,
    origin1: Origins.Clockwork,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Darius,
    set: 6,
    class1: Classes.Bodyguard,
    origin1: Origins.Syndicate,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Ezreal,
    set: 6,
    class1: Classes.Innovator,
    origin1: Origins.Scrap,
    cost: 1,
    range: 4,
  },
  {
    name: Names.Garen,
    set: 6,
    class1: Classes.Protector,
    origin1: Origins.Academy,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Graves,
    set: 6,
    class1: Classes.Twinshot,
    origin1: Origins.Academy,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Illaoi,
    set: 6,
    class1: Classes.Bruiser,
    origin1: Origins.Mercenary,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Kassadin,
    set: 6,
    class1: Classes.Protector,
    origin1: Origins.Mutant,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Poppy,
    set: 6,
    class1: Classes.Bodyguard,
    origin1: Origins.Yordle,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Singed,
    set: 6,
    class1: Classes.Innovator,
    origin1: Origins.Chemtech,
    cost: 1,
    range: 1,
  },
  {
    name: Names.TwistedFate,
    set: 6,
    class1: Classes.Arcanist,
    origin1: Origins.Syndicate,
    cost: 1,
    range: 3,
  },
  {
    name: Names.Twitch,
    set: 6,
    class1: Classes.Assassin,
    origin1: Origins.Chemtech,
    cost: 1,
    range: 3,
  },
  {
    name: Names.Ziggs,
    set: 6,
    class1: Classes.Arcanist,
    origin1: Origins.Scrap,
    origin2: Origins.Yordle,
    cost: 1,
    range: 4,
  },
  {
    name: Names.Blitzcrank,
    set: 6,
    class1: Classes.Bodyguard,
    class2: Classes.Protector,
    origin1: Origins.Scrap,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Katarina,
    set: 6,
    class1: Classes.Assassin,
    origin1: Origins.Academy,
    cost: 2,
    range: 1,
  },
  {
    name: Names.KogMaw,
    set: 6,
    class1: Classes.Twinshot,
    class2: Classes.Sniper,
    origin1: Origins.Mutant,
    cost: 2,
    range: 3,
  },
  {
    name: Names.Lulu,
    set: 6,
    class1: Classes.Enchanter,
    origin1: Origins.Yordle,
    cost: 2,
    range: 3,
  },
  {
    name: Names.Quinn,
    set: 6,
    class1: Classes.Challenger,
    origin1: Origins.Mercenary,
    cost: 2,
    range: 4,
  },
  {
    name: Names.Swain,
    set: 6,
    class1: Classes.Arcanist,
    origin1: Origins.Imperial,
    cost: 2,
    range: 2,
  },
  {
    name: Names.Talon,
    set: 6,
    class1: Classes.Assassin,
    origin1: Origins.Imperial,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Tristana,
    set: 6,
    class1: Classes.Sniper,
    origin1: Origins.Yordle,
    cost: 2,
    range: 4,
  },
  {
    name: Names.Trundle,
    set: 6,
    class1: Classes.Bruiser,
    origin1: Origins.Scrap,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Vi,
    set: 6,
    class1: Classes.Bruiser,
    origin1: Origins.Enforcer,
    origin2: Origins.Sister,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Warwick,
    set: 6,
    class1: Classes.Challenger,
    origin1: Origins.Chemtech,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Zilean,
    set: 6,
    class1: Classes.Innovator,
    origin1: Origins.Clockwork,
    cost: 2,
    range: 4,
  },
  {
    name: Names.Zyra,
    set: 6,
    class1: Classes.Scholar,
    origin1: Origins.Syndicate,
    cost: 2,
    range: 4,
  },
  {
    name: Names.Chogath,
    set: 6,
    class1: Classes.Colossus,
    class2: Classes.Bruiser,
    origin1: Origins.Mutant,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Ekko,
    set: 6,
    class1: Classes.Assassin,
    origin1: Origins.Scrap,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Gangplank,
    set: 6,
    class1: Classes.Twinshot,
    origin1: Origins.Mercenary,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Heimerdinger,
    set: 6,
    class1: Classes.Scholar,
    class2: Classes.Innovator,
    origin1: Origins.Yordle,
    cost: 3,
    range: 4,
  },
  {
    name: Names.Leona,
    set: 6,
    class1: Classes.Bodyguard,
    origin1: Origins.Academy,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Lissandra,
    set: 6,
    class1: Classes.Scholar,
    origin1: Origins.Chemtech,
    cost: 3,
    range: 3,
  },
  {
    name: Names.Heimerdinger,
    set: 6,
    class1: Classes.Scholar,
    class2: Classes.Innovator,
    origin1: Origins.Yordle,
    cost: 3,
    range: 4,
  },
  {
    name: Names.Malzahar,
    set: 6,
    class1: Classes.Arcanist,
    origin1: Origins.Mutant,
    cost: 3,
    range: 4,
  },
  {
    name: Names.MissFortune,
    set: 6,
    class1: Classes.Sniper,
    origin1: Origins.Mercenary,
    cost: 3,
    range: 3,
  },
  {
    name: Names.Samira,
    set: 6,
    class1: Classes.Challenger,
    origin1: Origins.Imperial,
    cost: 3,
    range: 3,
  },
  {
    name: Names.Shaco,
    set: 6,
    class1: Classes.Assassin,
    origin1: Origins.Syndicate,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Taric,
    set: 6,
    class1: Classes.Enchanter,
    origin1: Origins.Socialite,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Vex,
    set: 6,
    class1: Classes.Arcanist,
    origin1: Origins.Yordle,
    cost: 3,
    range: 2,
  },
  {
    name: Names.Zac,
    set: 6,
    class1: Classes.Bruiser,
    origin1: Origins.Chemtech,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Braum,
    set: 6,
    class1: Classes.Bodyguard,
    origin1: Origins.Syndicate,
    cost: 4,
    range: 1,
  },
  {
    name: Names.DrMundo,
    set: 6,
    class1: Classes.Bruiser,
    origin1: Origins.Mutant,
    origin2: Origins.Chemtech,
    cost: 4,
    range: 1,
  },
  {
    name: Names.Fiora,
    set: 6,
    class1: Classes.Challenger,
    origin1: Origins.Enforcer,
    cost: 4,
    range: 1,
  },
  {
    name: Names.Janna,
    set: 6,
    class1: Classes.Scholar,
    class2: Classes.Enchanter,
    origin1: Origins.Scrap,
    cost: 4,
    range: 3,
  },
  {
    name: Names.Jhin,
    set: 6,
    class1: Classes.Sniper,
    origin1: Origins.Clockwork,
    cost: 4,
    range: 4,
  },
  {
    name: Names.Lux,
    set: 6,
    class1: Classes.Arcanist,
    origin1: Origins.Academy,
    cost: 4,
    range: 4,
  },
  {
    name: Names.Orianna,
    set: 6,
    class1: Classes.Enchanter,
    origin1: Origins.Clockwork,
    cost: 4,
    range: 4,
  },
  {
    name: Names.Seraphine,
    set: 6,
    class1: Classes.Innovator,
    origin1: Origins.Socialite,
    cost: 4,
    range: 4,
  },
  {
    name: Names.Sion,
    set: 6,
    class1: Classes.Colossus,
    class2: Classes.Protector,
    origin1: Origins.Imperial,
    cost: 4,
    range: 1,
  },
  {
    name: Names.Urgot,
    set: 6,
    class1: Classes.Twinshot,
    origin1: Origins.Chemtech,
    cost: 4,
    range: 3,
  },
  {
    name: Names.Yone,
    set: 6,
    class1: Classes.Challenger,
    origin1: Origins.Academy,
    cost: 4,
    range: 1,
  },
  {
    name: Names.Akali,
    set: 6,
    class1: Classes.Assassin,
    origin1: Origins.Syndicate,
    cost: 5,
    range: 1,
  },
  {
    name: Names.Galio,
    set: 6,
    class1: Classes.Colossus,
    class2: Classes.Bodyguard,
    origin1: Origins.Socialite,
    cost: 5,
    range: 1,
  },
  {
    name: Names.Jayce,
    set: 6,
    class1: Classes.Transformer,
    class2: Classes.Innovator,
    origin1: Origins.Enforcer,
    cost: 5,
    range: 1,
  },
  {
    name: Names.Jinx,
    set: 6,
    class1: Classes.Twinshot,
    origin1: Origins.Scrap,
    origin2: Origins.Sister,
    cost: 5,
    range: 4,
  },
  {
    name: Names.KaiSa,
    set: 6,
    class1: Classes.Challenger,
    origin1: Origins.Mutant,
    cost: 5,
    range: 3,
  },
  {
    name: Names.TahmKench,
    set: 6,
    class1: Classes.Bruiser,
    origin1: Origins.Glutton,
    origin2: Origins.Mercenary,
    cost: 5,
    range: 1,
  },
  {
    name: Names.Veigar,
    set: 6,
    origin1: Origins.YordleLord,
    cost: 5,
    range: 4,
  },
  {
    name: Names.Viktor,
    set: 6,
    class1: Classes.Arcanist,
    origin1: Origins.Chemtech,
    cost: 5,
    range: 4,
  },
  {
    name: Names.Yuumi,
    set: 6,
    class1: Classes.Scholar,
    origin1: Origins.Cuddly,
    origin2: Origins.Academy,
    cost: 5,
    range: 4,
  },
];

export const SET65: Champion[] = [
  {
    name: Names.Brand,
    set: 6.5,
    class1: Classes.Arcanist,
    origin1: Origins.Debornair,
    cost: 1,
    range: 3,
  },
  {
    name: Names.Caitlyn,
    set: 6.5,
    class1: Classes.Sniper,
    origin1: Origins.Enforcer,
    cost: 1,
    range: 5,
  },
  {
    name: Names.Camille,
    set: 6.5,
    class1: Classes.Challenger,
    origin1: Origins.Clockwork,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Darius,
    set: 6.5,
    class1: Classes.Bodyguard,
    origin1: Origins.Syndicate,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Ezreal,
    set: 6.5,
    class1: Classes.Innovator,
    origin1: Origins.Scrap,
    cost: 1,
    range: 4,
  },
  {
    name: Names.Illaoi,
    set: 6.5,
    class1: Classes.Bruiser,
    origin1: Origins.Mercenary,
    cost: 1,
    range: 1,
  },
  {
    name: Names.JarvanIV,
    set: 6.5,
    origin1: Origins.Hextech,
    origin2: Origins.Striker,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Kassadin,
    set: 6.5,
    class1: Classes.Scholar,
    origin1: Origins.Mutant,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Nocturne,
    set: 6.5,
    class1: Classes.Assassin,
    origin1: Origins.Hextech,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Poppy,
    set: 6.5,
    class1: Classes.Bodyguard,
    origin1: Origins.Yordle,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Singed,
    set: 6.5,
    class1: Classes.Innovator,
    origin1: Origins.Chemtech,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Twitch,
    set: 6.5,
    class1: Classes.Assassin,
    origin1: Origins.Chemtech,
    cost: 1,
    range: 3,
  },
  {
    name: Names.Ziggs,
    set: 6.5,
    class1: Classes.Arcanist,
    origin1: Origins.Scrap,
    origin2: Origins.Yordle,
    cost: 1,
    range: 4,
  },
  {
    name: Names.Ashe,
    set: 6.5,
    class1: Classes.Sniper,
    origin1: Origins.Syndicate,
    cost: 2,
    range: 4,
  },
  {
    name: Names.Blitzcrank,
    set: 6.5,
    class1: Classes.Bodyguard,
    origin1: Origins.Scrap,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Corki,
    set: 6.5,
    class1: Classes.Twinshot,
    origin1: Origins.Yordle,
    cost: 2,
    range: 4,
  },
  {
    name: Names.Lulu,
    set: 6.5,
    class1: Classes.Enchanter,
    origin1: Origins.Yordle,
    cost: 2,
    range: 3,
  },
  {
    name: Names.Quinn,
    set: 6.5,
    class1: Classes.Challenger,
    origin1: Origins.Mercenary,
    cost: 2,
    range: 4,
  },
  {
    name: Names.RekSai,
    set: 6.5,
    class1: Classes.Bruiser,
    origin1: Origins.Mutant,
    origin2: Origins.Striker,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Sejuani,
    set: 6.5,
    class1: Classes.Bruiser,
    origin1: Origins.Hextech,
    origin2: Origins.Enforcer,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Swain,
    set: 6.5,
    class1: Classes.Arcanist,
    origin1: Origins.Hextech,
    cost: 2,
    range: 2,
  },
  {
    name: Names.Syndra,
    set: 6.5,
    class1: Classes.Scholar,
    origin1: Origins.Debornair,
    cost: 2,
    range: 4,
  },
  {
    name: Names.Talon,
    set: 6.5,
    class1: Classes.Assassin,
    origin1: Origins.Debornair,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Warwick,
    set: 6.5,
    class1: Classes.Challenger,
    origin1: Origins.Chemtech,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Zilean,
    set: 6.5,
    class1: Classes.Innovator,
    origin1: Origins.Clockwork,
    cost: 2,
    range: 4,
  },
  {
    name: Names.Zyra,
    set: 6.5,
    class1: Classes.Scholar,
    origin1: Origins.Syndicate,
    cost: 2,
    range: 4,
  },
  {
    name: Names.Chogath,
    set: 6.5,
    class1: Classes.Colossus,
    class2: Classes.Bruiser,
    origin1: Origins.Mutant,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Ekko,
    set: 6.5,
    class1: Classes.Assassin,
    class2: Classes.Innovator,
    origin1: Origins.Scrap,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Gangplank,
    set: 6.5,
    class1: Classes.Twinshot,
    origin1: Origins.Mercenary,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Gnar,
    set: 6.5,
    origin1: Origins.Yordle,
    origin2: Origins.Socialite,
    cost: 3,
    range: 3,
  },
  {
    name: Names.Leona,
    set: 6.5,
    class1: Classes.Bodyguard,
    origin1: Origins.Debornair,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Lucian,
    set: 6.5,
    class1: Classes.Twinshot,
    origin1: Origins.Hextech,
    cost: 3,
    range: 3,
  },
  {
    name: Names.Malzahar,
    set: 6.5,
    class1: Classes.Arcanist,
    origin1: Origins.Mutant,
    cost: 3,
    range: 4,
  },
  {
    name: Names.MissFortune,
    set: 6.5,
    class1: Classes.Sniper,
    origin1: Origins.Mercenary,
    cost: 3,
    range: 4,
  },
  {
    name: Names.Morgana,
    set: 6.5,
    class1: Classes.Enchanter,
    origin1: Origins.Syndicate,
    cost: 3,
    range: 2,
  },
  {
    name: Names.Senna,
    set: 6.5,
    class1: Classes.Enchanter,
    origin1: Origins.Socialite,
    cost: 3,
    range: 4,
  },
  {
    name: Names.Tryndamere,
    set: 6.5,
    class1: Classes.Challenger,
    origin1: Origins.Chemtech,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Vex,
    set: 6.5,
    class1: Classes.Arcanist,
    origin1: Origins.Yordle,
    cost: 3,
    range: 2,
  },
  {
    name: Names.Zac,
    set: 6.5,
    class1: Classes.Bruiser,
    origin1: Origins.Chemtech,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Ahri,
    set: 6.5,
    class1: Classes.Arcanist,
    origin1: Origins.Syndicate,
    cost: 4,
    range: 4,
  },
  {
    name: Names.Alistar,
    set: 6.5,
    class1: Classes.Colossus,
    origin1: Origins.Hextech,
    cost: 4,
    range: 1,
  },
  {
    name: Names.Braum,
    set: 6.5,
    class1: Classes.Bodyguard,
    origin1: Origins.Syndicate,
    cost: 4,
    range: 1,
  },
  {
    name: Names.Draven,
    set: 6.5,
    class1: Classes.Challenger,
    origin1: Origins.Debornair,
    cost: 4,
    range: 4,
  },
  {
    name: Names.Irelia,
    set: 6.5,
    origin1: Origins.Scrap,
    origin2: Origins.Striker,
    cost: 4,
    range: 1,
  },
  {
    name: Names.Jhin,
    set: 6.5,
    class1: Classes.Sniper,
    origin1: Origins.Clockwork,
    cost: 4,
    range: 5,
  },
  {
    name: Names.KhaZix,
    set: 6.5,
    class1: Classes.Assassin,
    origin1: Origins.Mutant,
    cost: 4,
    range: 1,
  },
  {
    name: Names.Orianna,
    set: 6.5,
    class1: Classes.Enchanter,
    origin1: Origins.Clockwork,
    cost: 4,
    range: 4,
  },
  {
    name: Names.Renata,
    set: 6.5,
    class1: Classes.Scholar,
    origin1: Origins.Chemtech,
    cost: 4,
    range: 3,
  },
  {
    name: Names.Seraphine,
    set: 6.5,
    class1: Classes.Innovator,
    origin1: Origins.Socialite,
    cost: 4,
    range: 4,
  },
  {
    name: Names.Sivir,
    set: 6.5,
    origin1: Origins.Hextech,
    origin2: Origins.Striker,
    cost: 4,
    range: 4,
  },
  {
    name: Names.Vi,
    set: 6.5,
    class1: Classes.Bruiser,
    origin1: Origins.Enforcer,
    origin2: Origins.Rivals,
    cost: 4,
    range: 1,
  },
  {
    name: Names.Galio,
    set: 6.5,
    class1: Classes.Colossus,
    class2: Classes.Bodyguard,
    origin1: Origins.Socialite,
    cost: 5,
    range: 1,
  },
  {
    name: Names.Jayce,
    set: 6.5,
    class1: Classes.Transformer,
    class2: Classes.Innovator,
    origin1: Origins.Enforcer,
    cost: 5,
    range: 1,
  },
  {
    name: Names.Jinx,
    set: 6.5,
    class1: Classes.Twinshot,
    origin1: Origins.Scrap,
    origin2: Origins.Rivals,
    cost: 5,
    range: 4,
  },
  {
    name: Names.KaiSa,
    set: 6.5,
    class1: Classes.Challenger,
    origin1: Origins.Mutant,
    cost: 5,
    range: 3,
  },
  {
    name: Names.Silco,
    set: 6.5,
    class1: Classes.Mastermind,
    class2: Classes.Scholar,
    cost: 5,
    range: 4,
  },
  {
    name: Names.TahmKench,
    set: 6.5,
    class1: Classes.Bruiser,
    origin1: Origins.Glutton,
    origin2: Origins.Mercenary,
    cost: 5,
    range: 1,
  },
  {
    name: Names.Veigar,
    set: 6.5,
    origin1: Origins.YordleLord,
    cost: 5,
    range: 4,
  },
  {
    name: Names.Viktor,
    set: 6.5,
    class1: Classes.Arcanist,
    origin1: Origins.Chemtech,
    cost: 5,
    range: 4,
  },
  {
    name: Names.Zeri,
    set: 6.5,
    class1: Classes.Sniper,
    origin1: Origins.Debornair,
    cost: 5,
    range: 5,
  },
];

export const SET7: Champion[] = [
  {
    name: Names.Aatrox,
    set: 7,
    class1: Classes.Warrior,
    origin1: Origins.Shimmerscale,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Ezreal,
    set: 7,
    class1: Classes.Swiftshot,
    origin1: Origins.Tempest,
    cost: 1,
    range: 3,
  },
  {
    name: Names.Heimerdinger,
    set: 7,
    class1: Classes.Mage,
    origin1: Origins.Trainer,
    cost: 1,
    range: 4,
  },
  {
    name: Names.Karma,
    set: 7,
    class1: Classes.Dragonmancer,
    origin1: Origins.Jade,
    cost: 1,
    range: 4,
  },
  {
    name: Names.Leona,
    set: 7,
    class1: Classes.Guardian,
    origin1: Origins.Mirage,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Nidalee,
    set: 7,
    class1: Classes.Shapeshifter,
    origin1: Origins.Astral,
    cost: 1,
    range: 4,
  },
  {
    name: Names.Sejuani,
    set: 7,
    class1: Classes.Cavalier,
    origin1: Origins.Guild,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Senna,
    set: 7,
    class1: Classes.Cannoneer,
    origin1: Origins.Ragewing,
    cost: 1,
    range: 4,
  },
  {
    name: Names.Sett,
    set: 7,
    class1: Classes.Dragonmancer,
    origin1: Origins.Ragewing,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Skarner,
    set: 7,
    class1: Classes.Bruiser,
    origin1: Origins.Astral,
    cost: 1,
    range: 1,
  },
  {
    name: Names.TahmKench,
    set: 7,
    class1: Classes.Bruiser,
    origin1: Origins.Revel,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Taric,
    set: 7,
    class1: Classes.Guardian,
    origin1: Origins.Jade,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Vladimir,
    set: 7,
    class1: Classes.Mage,
    origin1: Origins.Astral,
    cost: 1,
    range: 2,
  },
  {
    name: Names.Ashe,
    set: 7,
    class1: Classes.Swiftshot,
    origin1: Origins.Jade,
    cost: 2,
    range: 4,
  },
  {
    name: Names.Braum,
    set: 7,
    class1: Classes.Guardian,
    origin1: Origins.Scalescorn,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Gnar,
    set: 7,
    class1: Classes.Shapeshifter,
    origin1: Origins.Jade,
    cost: 2,
    range: 2,
  },
  {
    name: Names.Jinx,
    set: 7,
    class1: Classes.Cannoneer,
    origin1: Origins.Revel,
    cost: 2,
    range: 4,
  },
  {
    name: Names.Kayn,
    set: 7,
    class1: Classes.Assassin,
    origin1: Origins.Ragewing,
    origin2: Origins.Shimmerscale,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Lillia,
    set: 7,
    class1: Classes.Cavalier,
    class2: Classes.Mage,
    origin1: Origins.Scalescorn,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Nami,
    set: 7,
    class1: Classes.Mage,
    class2: Classes.Mystic,
    origin1: Origins.Astral,
    cost: 2,
    range: 3,
  },
  {
    name: Names.Qiyana,
    set: 7,
    class1: Classes.Assassin,
    origin1: Origins.Tempest,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Shen,
    set: 7,
    class1: Classes.Warrior,
    class2: Classes.Bruiser,
    origin1: Origins.Ragewing,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Thresh,
    set: 7,
    class1: Classes.Guardian,
    origin1: Origins.Whispers,
    cost: 2,
    range: 2,
  },
  {
    name: Names.Tristana,
    set: 7,
    class1: Classes.Cannoneer,
    origin1: Origins.Trainer,
    cost: 2,
    range: 4,
  },
  {
    name: Names.Twitch,
    set: 7,
    class1: Classes.Swiftshot,
    origin1: Origins.Guild,
    cost: 2,
    range: 3,
  },
  {
    name: Names.Yone,
    set: 7,
    class1: Classes.Warrior,
    origin1: Origins.Mirage,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Anivia,
    set: 7,
    class1: Classes.Evoker,
    class2: Classes.Legend,
    origin1: Origins.Jade,
    cost: 3,
    range: 4,
  },
  {
    name: Names.Diana,
    set: 7,
    class1: Classes.Assassin,
    origin1: Origins.Scalescorn,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Elise,
    set: 7,
    class1: Classes.Shapeshifter,
    origin1: Origins.Whispers,
    cost: 3,
    range: 2,
  },
  {
    name: Names.Illaoi,
    set: 7,
    class1: Classes.Bruiser,
    origin1: Origins.Astral,
    cost: 3,
    range: 1,
  },
  {
    name: Names.LeeSin,
    set: 7,
    class1: Classes.Dragonmancer,
    origin1: Origins.Tempest,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Lulu,
    set: 7,
    class1: Classes.Mystic,
    class2: Classes.Evoker,
    origin1: Origins.Trainer,
    cost: 3,
    range: 3,
  },
  {
    name: Names.Nunu,
    set: 7,
    class1: Classes.Cavalier,
    origin1: Origins.Mirage,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Olaf,
    set: 7,
    class1: Classes.Bruiser,
    class2: Classes.Warrior,
    origin1: Origins.Scalescorn,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Ryze,
    set: 7,
    class1: Classes.Mage,
    origin1: Origins.Guild,
    cost: 3,
    range: 4,
  },
  {
    name: Names.Swain,
    set: 7,
    class1: Classes.Dragonmancer,
    class2: Classes.Shapeshifter,
    origin1: Origins.Ragewing,
    cost: 3,
    range: 4,
  },
  {
    name: Names.Sylas,
    set: 7,
    class1: Classes.Mage,
    class2: Classes.Bruiser,
    origin1: Origins.Whispers,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Varus,
    set: 7,
    class1: Classes.Swiftshot,
    origin1: Origins.Astral,
    cost: 3,
    range: 3,
  },
  {
    name: Names.Volibear,
    set: 7,
    class1: Classes.Dragonmancer,
    class2: Classes.Legend,
    origin1: Origins.Shimmerscale,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Corki,
    set: 7,
    class1: Classes.Cannoneer,
    origin1: Origins.Revel,
    cost: 4,
    range: 4,
  },
  {
    name: Names.Hecarim,
    set: 7,
    class1: Classes.Cavalier,
    origin1: Origins.Ragewing,
    cost: 4,
    range: 1,
  },
  {
    name: Names.Neeko,
    set: 7,
    class1: Classes.Shapeshifter,
    origin1: Origins.Jade,
    cost: 4,
    range: 2,
  },
  {
    name: Names.Ornn,
    set: 7,
    class1: Classes.Bruiser,
    class2: Classes.Legend,
    origin1: Origins.Tempest,
    cost: 4,
    range: 1,
  },
  {
    name: Names.Sona,
    set: 7,
    class1: Classes.Evoker,
    origin1: Origins.Revel,
    cost: 4,
    range: 4,
  },
  {
    name: Names.Talon,
    set: 7,
    class1: Classes.Assassin,
    origin1: Origins.Guild,
    cost: 4,
    range: 1,
  },
  {
    name: Names.Xayah,
    set: 7,
    class1: Classes.Swiftshot,
    origin1: Origins.Ragewing,
    cost: 4,
    range: 3,
  },
  {
    name: Names.Bard,
    set: 7,
    class1: Classes.Bard,
    class2: Classes.Mystic,
    origin1: Origins.Guild,
    cost: 5,
    range: 4,
  },
  {
    name: Names.Pyke,
    set: 7,
    class1: Classes.Assassin,
    origin1: Origins.Whispers,
    cost: 5,
    range: 1,
  },
  {
    name: Names.Soraka,
    set: 7,
    class1: Classes.Starcaller,
    origin1: Origins.Jade,
    cost: 5,
    range: 4,
  },
  {
    name: Names.Yasuo,
    set: 7,
    class1: Classes.Dragonmancer,
    class2: Classes.Warrior,
    origin1: Origins.Mirage,
    cost: 5,
    range: 1,
  },
  {
    name: Names.Zoe,
    set: 7,
    class1: Classes.SpellThief,
    class2: Classes.Mage,
    origin1: Origins.Shimmerscale,
    cost: 5,
    range: 4,
  },
  {
    name: Names.Daeja,
    set: 7,
    origin1: Origins.Dragon,
    origin2: Origins.Mirage,
    cost: 8,
    range: 4,
  },
  {
    name: Names.Idas,
    set: 7,
    class1: Classes.Guardian,
    origin1: Origins.Dragon,
    origin2: Origins.Shimmerscale,
    cost: 8,
    range: 1,
  },
  {
    name: Names.ShiOhYu,
    set: 7,
    class1: Classes.Mystic,
    origin1: Origins.Dragon,
    origin2: Origins.Jade,
    cost: 8,
    range: 1,
  },
  {
    name: Names.Syfen,
    set: 7,
    class1: Classes.Bruiser,
    origin1: Origins.Dragon,
    origin2: Origins.Whispers,
    cost: 8,
    range: 1,
  },
  {
    name: Names.AoShin,
    set: 7,
    origin1: Origins.Dragon,
    origin2: Origins.Tempest,
    cost: 10,
    range: 4,
  },
  {
    name: Names.AurelionSol,
    set: 7,
    class1: Classes.Evoker,
    origin1: Origins.Dragon,
    origin2: Origins.Astral,
    cost: 10,
    range: 4,
  },
  {
    name: Names.Shyvana,
    set: 7,
    class1: Classes.Shapeshifter,
    origin1: Origins.Dragon,
    origin2: Origins.Ragewing,
    cost: 10,
    range: 1,
  },
];

export const SET75: Champion[] = [
  {
    name: Names.Ezreal,
    set: 7.5,
    class1: Classes.Swiftshot,
    origin1: Origins.Tempest,
    cost: 1,
    range: 3,
  },
  {
    name: Names.Karma,
    set: 7.5,
    class1: Classes.Dragonmancer,
    origin1: Origins.Jade,
    cost: 1,
    range: 4,
  },
  {
    name: Names.Leona,
    set: 7.5,
    class1: Classes.Guardian,
    origin1: Origins.Mirage,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Malphite,
    set: 7.5,
    class1: Classes.Bruiser,
    origin1: Origins.Lagoon,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Nasus,
    set: 7.5,
    class1: Classes.Guardian,
    origin1: Origins.Shimmerscale,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Nidalee,
    set: 7.5,
    class1: Classes.Shapeshifter,
    origin1: Origins.Astral,
    cost: 1,
    range: 4,
  },
  {
    name: Names.Sejuani,
    set: 7.5,
    class1: Classes.Cavalier,
    origin1: Origins.Guild,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Senna,
    set: 7.5,
    class1: Classes.Cannoneer,
    origin1: Origins.Ragewing,
    cost: 1,
    range: 4,
  },
  {
    name: Names.Sett,
    set: 7.5,
    class1: Classes.Dragonmancer,
    origin1: Origins.Ragewing,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Skarner,
    set: 7.5,
    class1: Classes.Bruiser,
    origin1: Origins.Astral,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Taliyah,
    set: 7.5,
    class1: Classes.Mage,
    origin1: Origins.Lagoon,
    cost: 1,
    range: 4,
  },
  {
    name: Names.Vladimir,
    set: 7.5,
    class1: Classes.Mage,
    origin1: Origins.Astral,
    cost: 1,
    range: 2,
  },
  {
    name: Names.Wukong,
    set: 7.5,
    class1: Classes.Warrior,
    origin1: Origins.Jade,
    cost: 1,
    range: 1,
  },
  {
    name: Names.Aphelios,
    set: 7.5,
    class1: Classes.Cannoneer,
    origin1: Origins.Darkflight,
    cost: 2,
    range: 4,
  },
  {
    name: Names.Braum,
    set: 7.5,
    class1: Classes.Guardian,
    origin1: Origins.Scalescorn,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Gnar,
    set: 7.5,
    class1: Classes.Shapeshifter,
    origin1: Origins.Jade,
    cost: 2,
    range: 2,
  },
  {
    name: Names.Jax,
    set: 7.5,
    class1: Classes.Bruiser,
    origin1: Origins.Jade,
    origin2: Origins.Shimmerscale,
    cost: 2,
    range: 1,
  },
  {
    name: Names.KaiSa,
    set: 7.5,
    class1: Classes.Dragonmancer,
    origin1: Origins.Lagoon,
    cost: 2,
    range: 4,
  },
  {
    name: Names.Lillia,
    set: 7.5,
    class1: Classes.Cavalier,
    class2: Classes.Mage,
    origin1: Origins.Scalescorn,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Lux,
    set: 7.5,
    class1: Classes.Mage,
    origin1: Origins.Astral,
    cost: 2,
    range: 4,
  },
  {
    name: Names.Qiyana,
    set: 7.5,
    class1: Classes.Assassin,
    origin1: Origins.Tempest,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Rell,
    set: 7.5,
    class1: Classes.Cavalier,
    origin1: Origins.Darkflight,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Twitch,
    set: 7.5,
    class1: Classes.Swiftshot,
    origin1: Origins.Guild,
    cost: 2,
    range: 3,
  },
  {
    name: Names.Yone,
    set: 7.5,
    class1: Classes.Warrior,
    origin1: Origins.Mirage,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Zac,
    set: 7.5,
    class1: Classes.Guardian,
    origin1: Origins.Lagoon,
    cost: 2,
    range: 1,
  },
  {
    name: Names.Zyra,
    set: 7.5,
    class1: Classes.Evoker,
    origin1: Origins.Whispers,
    cost: 2,
    range: 4,
  },
  {
    name: Names.Diana,
    set: 7.5,
    class1: Classes.Assassin,
    origin1: Origins.Scalescorn,
    cost: 3,
    range: 1,
  },
  {
    name: Names.LeeSin,
    set: 7.5,
    class1: Classes.Dragonmancer,
    origin1: Origins.Tempest,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Nunu,
    set: 7.5,
    class1: Classes.Cavalier,
    origin1: Origins.Mirage,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Olaf,
    set: 7.5,
    class1: Classes.Bruiser,
    class2: Classes.Warrior,
    origin1: Origins.Scalescorn,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Rakan,
    set: 7.5,
    class1: Classes.Guardian,
    class2: Classes.Mystic,
    origin1: Origins.Ragewing,
    cost: 3,
    range: 2,
  },
  {
    name: Names.Rengar,
    set: 7.5,
    class1: Classes.Assassin,
    origin1: Origins.Darkflight,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Seraphine,
    set: 7.5,
    class1: Classes.Evoker,
    class2: Classes.Mystic,
    origin1: Origins.Lagoon,
    cost: 3,
    range: 3,
  },
  {
    name: Names.Sylas,
    set: 7.5,
    class1: Classes.Mage,
    class2: Classes.Bruiser,
    origin1: Origins.Whispers,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Varus,
    set: 7.5,
    class1: Classes.Swiftshot,
    origin1: Origins.Astral,
    cost: 3,
    range: 3,
  },
  {
    name: Names.Volibear,
    set: 7.5,
    class1: Classes.Dragonmancer,
    origin1: Origins.Shimmerscale,
    cost: 3,
    range: 1,
  },
  {
    name: Names.Zeri,
    set: 7.5,
    class1: Classes.Cannoneer,
    origin1: Origins.Lagoon,
    cost: 3,
    range: 4,
  },
  {
    name: Names.Graves,
    set: 7.5,
    class1: Classes.Cannoneer,
    origin1: Origins.Tempest,
    cost: 4,
    range: 3,
  },
  {
    name: Names.Hecarim,
    set: 7.5,
    class1: Classes.Cavalier,
    origin1: Origins.Ragewing,
    cost: 4,
    range: 1,
  },
  {
    name: Names.Jayce,
    set: 7.5,
    class1: Classes.Shapeshifter,
    origin1: Origins.Guild,
    cost: 4,
    range: 3,
  },
  {
    name: Names.Nilah,
    set: 7.5,
    class1: Classes.Assassin,
    origin1: Origins.Lagoon,
    cost: 4,
    range: 2,
  },
  {
    name: Names.Pantheon,
    set: 7.5,
    class1: Classes.Warrior,
    origin1: Origins.Whispers,
    cost: 4,
    range: 1,
  },
  {
    name: Names.Xayah,
    set: 7.5,
    class1: Classes.Swiftshot,
    origin1: Origins.Ragewing,
    cost: 4,
    range: 3,
  },
  {
    name: Names.Bard,
    set: 7.5,
    class1: Classes.Bard,
    class2: Classes.Mystic,
    origin1: Origins.Guild,
    cost: 5,
    range: 4,
  },
  {
    name: Names.Soraka,
    set: 7.5,
    class1: Classes.Starcaller,
    origin1: Origins.Jade,
    cost: 5,
    range: 4,
  },
  {
    name: Names.Yasuo,
    set: 7.5,
    class1: Classes.Dragonmancer,
    class2: Classes.Warrior,
    origin1: Origins.Mirage,
    cost: 5,
    range: 1,
  },
  {
    name: Names.Zoe,
    set: 7.5,
    class1: Classes.SpellThief,
    class2: Classes.Mage,
    origin1: Origins.Shimmerscale,
    cost: 5,
    range: 4,
  },
  {
    name: Names.Nomsy,
    set: 7.5,
    class1: Classes.Prodigy,
    class2: Classes.Mage,
    origin1: Origins.Dragon,
    cost: 6,
    range: 3,
  },
  {
    name: Names.Nomsy,
    set: 7.5,
    class1: Classes.Prodigy,
    class2: Classes.Evoker,
    origin1: Origins.Dragon,
    cost: 6,
    range: 3,
  },
  {
    name: Names.Nomsy,
    set: 7.5,
    class1: Classes.Prodigy,
    class2: Classes.Cannoneer,
    origin1: Origins.Dragon,
    cost: 6,
    range: 3,
  },
  {
    name: Names.Zippy,
    set: 7.5,
    origin1: Origins.Dragon,
    origin2: Origins.Guild,
    cost: 6,
    range: 1,
  },
  {
    name: Names.Daeja,
    set: 7.5,
    origin1: Origins.Dragon,
    origin2: Origins.Mirage,
    cost: 7,
    range: 4,
  },
  {
    name: Names.DragonTyrantSwain,
    set: 7.5,
    origin1: Origins.Dragon,
    origin2: Origins.Darkflight,
    cost: 7,
    range: 2,
  },
  {
    name: Names.Idas,
    set: 7.5,
    class1: Classes.Guardian,
    origin1: Origins.Dragon,
    origin2: Origins.Shimmerscale,
    cost: 7,
    range: 1,
  },
  {
    name: Names.ShiOhYu,
    set: 7.5,
    class1: Classes.Mystic,
    origin1: Origins.Dragon,
    origin2: Origins.Jade,
    cost: 7,
    range: 1,
  },
  {
    name: Names.Sohm,
    set: 7.5,
    class1: Classes.Mage,
    origin1: Origins.Dragon,
    origin2: Origins.Lagoon,
    cost: 7,
    range: 4,
  },
  {
    name: Names.Syfen,
    set: 7.5,
    class1: Classes.Bruiser,
    origin1: Origins.Dragon,
    origin2: Origins.Whispers,
    cost: 7,
    range: 1,
  },
  {
    name: Names.AoShin,
    set: 7.5,
    origin1: Origins.Dragon,
    origin2: Origins.Tempest,
    cost: 8,
    range: 4,
  },
  {
    name: Names.AurelionSol,
    set: 7.5,
    class1: Classes.Evoker,
    origin1: Origins.Dragon,
    origin2: Origins.Astral,
    cost: 8,
    range: 4,
  },
  {
    name: Names.Shyvana,
    set: 7.5,
    class1: Classes.Shapeshifter,
    origin1: Origins.Dragon,
    origin2: Origins.Ragewing,
    cost: 8,
    range: 1,
  },
  {
    name: Names.Terra,
    set: 7.5,
    class1: Classes.Monolith,
    origin1: Origins.Dragon,
    cost: 8,
    range: 1,
  },
];
